language: python
env:
  matrix:
     - TERRAFORM_FILE=testing/aws.tf ANSIBLE_PLAYBOOK=sample.yml
     - TERRAFORM_FILE=testing/do.tf  ANSIBLE_PLAYBOOK=sample.yml
     - TERRAFORM_FILE=testing/gce.tf ANSIBLE_PLAYBOOK=sample.yml
    # - TERRAFORM_FILE=testing/aws.tf ANSIBLE_PLAYBOOK=kubernetes.yml
    # - TERRAFORM_FILE=testing/do.tf  ANSIBLE_PLAYBOOK=kubernetes.yml
    # - TERRAFORM_FILE=testing/gce.tf ANSIBLE_PLAYBOOK=kubernetes.yml

install: "pip install -r requirements.txt"

script: testing/run-tests.sh

# Just once doesn't always work
after_script:
  - terraform destroy --force || true
  - terraform destroy --force

after_success: echo "slack notification here"

addons:
  apt:
    packages:
      - unzip
