---
- name: give consul privileges to run docker commands
  when: "{{ current_role in ['consul', 'logstash'] }}"
  become: yes
  copy:
    content: |
      consul ALL=(ALL)    NOPASSWD:   /bin/docker
    dest: /etc/sudoers.d/consul-docker-auth
    validate: visudo -c -f "%s"
  tags:
    - bootstrap
    - consul
    - distributive
    - docker

# Needed for upgrade from Mantl <1.0
- name: remove symlink to deprecated distributive checklist
  become: yes
  file:
    state: absent
    path: /etc/distributive.d/{{ current_role }}.json
  tags:
    - bootstrap
    - distributive

# Needed for upgrade from Mantl <1.0
- name: de-register deprecated distributive tests with consul
  become: yes
  file:
    path: "/etc/consul/distributive-{{ current_role }}-check.json"
    state: absent
  notify:
    - reload consul
  tags:
    - bootstrap
    - consul
    - distributive

- name: install distributive, health check packages for current role
  become: yes
  yum:
    state: present
    name: "{{ item }}"
  tags:
    - distributive
    - bootstrap
  with_items:
    - "{{ distributive_package }}"
    - "distributive-{{ current_role }}-{{ checklist_versions[current_role] }}"

- name: create consul configuration directory
  become: yes
  file:
    path: /etc/consul
    state: directory
    mode: 0770
  tags:
    - bootstrap
    - consul
    - distributive

- name: configure consul health check
  become: yes
  template:
    src: consul-healthcheck.json.j2
    dest: /etc/consul/distributive-{{ current_role }}-check.json
  tags:
    - bootstrap
    - consul
    - distributive
