---
- name: reload consul
  sudo: yes
  command: systemctl reload consul

- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: restart traefik
  sudo: yes
  command: systemctl restart traefik
